
services:
  service-registry:
    build: ./gateway_service_registry
    container_name: service-registry
    ports:
      - "8761:8761"
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD = 1234
      - MYSQL_PASSWORD= 1234
      - MYSQL_DATABASE=mysql
#    ports:
#      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "8005:8005"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/ITuser?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=1234
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka/
    depends_on:
      - service-registry
      - mysql
    networks:
      - app-network

  student-lifecycle-service:
    build: ./StudentLifecylce
    container_name: student-lifecycle-service
    ports:
      - "8087:8087"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/saintcandidate?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=1234
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka/
    depends_on:
      - service-registry
      - mysql
    networks:
      - app-network

  task-service:
    build: ./TaskService
    container_name: task-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/SaintTask?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=1234
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka/
    depends_on:
      - service-registry
      - mysql
    networks:
      - app-network

  gateway:
    build: ./gateway
    container_name: gateway
    ports:
      - "8080:8080"
    environment:
      - USER_SERVICE_URI=http://user-service:8005
      - STUDENT_LIFECYCLE_URI=http://student-lifecycle-service:8087
      - TASK_SERVICE_URI=http://task-service:8082
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka/
    depends_on:
      - user-service
      - student-lifecycle-service
      - task-service
      - service-registry
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports: [ "8081:81" ]
    environment:
      - PMA_ARBITRARY = 1
      - PMA_ABSOLUTE_URI = http://localhost:8081
      - PMA_HOST = mysql
      - PMA_PORT = 3306
    restart: always
    depends_on:
      - mysql
    networks: [ app-network ]

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
