spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: ["http://localhost:4200", "http://localhost:4300"]
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

      routes:
        - id: user-service
          uri: ${USER_SERVICE_URI:http://localhost:8005}
          predicates:
            - Path=/auth/**
          filters: []
        - id: user-service-api-docs
          uri: ${USER_SERVICE_URI:http://localhost:8005}
          predicates:
            - Path=/auth/v3/api-docs/**
          filters: []
        - id: user-service-openapi
          uri: ${USER_SERVICE_URI:http://localhost:8005}
          predicates:
            - Path=/auth/swagger-ui.html
          filters: []

        - id: student-lifecycle-service
          uri: ${STUDENT_LIFECYCLE_URI:http://localhost:8087}
          predicates:
            - Path=/lifecycle/**
          filters: []
        - id: student-service-api-docs
          uri: ${STUDENT_LIFECYCLE_URI:http://localhost:8087}
          predicates:
            - Path=/lifecycle/v3/api-docs/**
          filters: []
        - id: student-service-openapi
          uri: ${STUDENT_LIFECYCLE_URI:http://localhost:8087}
          predicates:
            - Path=/lifecycle/swagger-ui.html
          filters: []

        - id: task-service
          uri: ${TASK_SERVICE_URI:http://localhost:8082}
          predicates:
            - Path=/Task/**
          filters: []
        - id: task-service-api-docs
          uri: ${TASK_SERVICE_URI:http://localhost:8082}
          predicates:
            - Path=/Task/v3/api-docs/**
          filters: []
        - id: task-service-openapi
          uri: ${TASK_SERVICE_URI:http://localhost:8082}
          predicates:
            - Path=/Task/swagger-ui.html
          filters: []

        - id: openapi
          uri: ${OPENAPI_URI:http://localhost:8080}
          predicates:
            - Path=/v3/api-docs/**
          filters: []

  application:
    name: GATEWAY

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE:http://localhost:8761/eureka/}
#      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
