spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: ["http://localhost:4200", "http://localhost:4300"]
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

      routes:
        - id: user-service
          uri: http://user-service:8005
          predicates:
            - Path=/auth/**
          filters: []
        - id: user-service-api-docs
          uri: http://user-service:8005
          predicates:
            - Path=/auth/v3/api-docs/**
          filters: []
        - id: user-service-openapi
          uri: http://user-service:8005
          predicates:
            - Path=/auth/swagger-ui.html
          filters: []

        - id: student-lifecycle-service
          uri: http://studentlifecycle:8087
          predicates:
            - Path=/lifecycle/**
          filters: []
        - id: student-service-api-docs
          uri: http://studentlifecycle:8087
          predicates:
            - Path=/lifecycle/v3/api-docs/**
          filters: []
        - id: student-service-openapi
          uri: http://studentlifecycle:8087
          predicates:
            - Path=/lifecycle/swagger-ui.html
          filters: []

        - id: task-service
          uri: http://taskservice:8082
          predicates:
            - Path=/Task/**
          filters: []
        - id: task-service-api-docs
          uri: http://taskservice:8082
          predicates:
            - Path=/Task/v3/api-docs/**
          filters: []
        - id: task-service-openapi
          uri: http://taskservice:8082
          predicates:
            - Path=/Task/swagger-ui.html
          filters: []

        - id: openapi
          uri: http://gateway:8080
          predicates:
            - Path=/v3/api-docs/**
          filters: []

  application:
    name: GATEWAY

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://eureka:8761/eureka/}
