spring:
  application:
    name: StudentLifecycle

eureka:
  client:
    service-url:
      defaultZone : http://service-registry:8761/eureka/
#      ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
#      defaultZone : http://eureka-server:8761/eureka/
#      defaultZone : http://localhost:8761/eureka/


server:
  port: 8087